---
title: InternalError.prototype
slug: conflicting/Web/JavaScript/Reference/Global_Objects/InternalError
tags:
  - Error
  - InternalError
  - JavaScript
  - Propriété
  - Reference
translation_of: Web/JavaScript/Reference/Global_Objects/InternalError
translation_of_original: Web/JavaScript/Reference/Global_Objects/InternalError/prototype
original_slug: Web/JavaScript/Reference/Objets_globaux/InternalError/prototype
---
<div>{{JSRef}} {{non-standard_header}}</div>

<p>La propriété <code><strong>InternalError.prototype</strong></code> représente le prototype du constructeur {{jsxref("InternalError")}}.</p>

<div>{{js_property_attributes(0,0,0)}}</div>

<h2 id="Description">Description</h2>

<p>Toutes les instances de {{jsxref("InternalError")}} héritent de {{jsxref("InternalError.prototype")}}. Ce prototype peut être utilisé pour ajouter des propriétés et/ou des méthodes à toutes les instances.</p>

<h2 id="Propriétés">Propriétés</h2>

<dl>
 <dt><code>InternalError.prototype.constructor</code></dt>
 <dd>Définit la fonction qui permet de créer une instance du prototype.</dd>
 <dt>{{jsxref("Error.prototype.message", "InternalError.prototype.message")}}</dt>
 <dd>Un nom d'erreur. Bien que ECMA-262 spécifie que <code>InternalError</code> devrait fournir une propriété propre pour <code>message</code>. L'implémentation de<a href="/fr/docs/SpiderMonkey"> SpiderMonkey</a> fait que cette propriété est héritée via {{jsxref("Error.prototype.message")}}.</dd>
 <dt>{{jsxref("Error.prototype.name", "InternalError.prototype.name")}}</dt>
 <dd>Un nom d'erreur. Hérité via {{jsxref("Error")}}.</dd>
 <dt>{{jsxref("Error.prototype.fileName", "InternalError.prototype.fileName")}}</dt>
 <dd>Le chemin du fichier à l'origine de l'erreur. Héritée via {{jsxref("Error")}}.</dd>
 <dt>{{jsxref("Error.prototype.lineNumber", "InternalError.prototype.lineNumber")}}</dt>
 <dd>Le numéro de la ligne dans le fichier pour le code qui a déclenché l'erreur. Héritée via {{jsxref("Error")}}.</dd>
 <dt>{{jsxref("Error.prototype.columnNumber", "InternalError.prototype.columnNumber")}}</dt>
 <dd>Le numéro de la colonne dans la ligne du fichier pour le code qui a déclenché l'erreur. Héritée via {{jsxref("Error")}}.</dd>
 <dt>{{jsxref("Error.prototype.stack", "InternalError.prototype.stack")}}</dt>
 <dd>Pile d'appels (stack trace). Héritée via {{jsxref("Error")}}.</dd>
</dl>

<h2 id="Méthodes">Méthodes</h2>

<p>Bien que l'objet prototype <code>InternalError</code> ne contienne aucune méthode qui lui soit propre, les instances de {{jsxref("InternalError")}} héritent de méthodes grâce à la chaîne de prototypes.</p>

<h2 id="Spécifications">Spécifications</h2>

<p>Cette propriété ne fait partie d'aucune spécification.</p>

<h2 id="Compatibilité_des_navigateurs">Compatibilité des navigateurs</h2>

<p>{{Compat("javascript.builtins.InternalError")}}</p>

<h2 id="Voir_aussi">Voir aussi</h2>

<ul>
 <li>{{jsxref("Error.prototype")}}</li>
 <li>{{jsxref("Function.prototype")}}</li>
</ul>
