---
title: RangeError.prototype
slug: conflicting/Web/JavaScript/Reference/Global_Objects/RangeError
tags:
  - Error
  - JavaScript
  - Propriété
  - Prototype
  - RangeError
  - Reference
translation_of: Web/JavaScript/Reference/Global_Objects/RangeError
translation_of_original: Web/JavaScript/Reference/Global_Objects/RangeError/prototype
original_slug: Web/JavaScript/Reference/Objets_globaux/RangeError/prototype
---
<div>{{JSRef}}</div>

<p>La propriété <code><strong>RangeError.prototype</strong></code> représente le prototype du constructeur {{jsxref("RangeError")}}.</p>

<div>{{js_property_attributes(0, 0, 0)}}</div>

<h2 id="Description">Description</h2>

<p>Chacune des instances de {{jsxref("RangeError")}} hérite de <code>RangeError.prototype</code>. Le prototype peut être utilisé afin d'ajouter des propriétés et/ou des méthodes à toutes les instances.</p>

<h2 id="Propriétés">Propriétés</h2>

<dl>
 <dt><code>RangeError.prototype.constructor</code></dt>
 <dd>Définit la fonction qui a créé le prototype de l'instance.</dd>
 <dt>{{jsxref("Error.prototype.message", "RangeError.prototype.message")}}</dt>
 <dd>Le nom de l'erreur. Bien que ECMA-262 spécifie que {{jsxref("RangeError")}} devrait fournir sa propre propriété <code>message</code>, dans <a href="/fr/docs/SpiderMonkey" title="SpiderMonkey">SpiderMonkey</a>, il l'hérite depuis {{jsxref("Error.prototype.message")}}.</dd>
 <dt>{{jsxref("Error.prototype.name", "RangeError.prototype.name")}}</dt>
 <dd>Le nom de l'erreur, hérité depuis {{jsxref("Error")}}.</dd>
 <dt>{{jsxref("Error.prototype.fileName", "RangeError.prototype.fileName")}}</dt>
 <dd>Le chemin vers le fichier qui a causé l'erreur, hérité depuis {{jsxref("Error")}}.</dd>
 <dt>{{jsxref("Error.prototype.lineNumber", "RangeError.prototype.lineNumber")}}</dt>
 <dd>Le numéro de la ligne de code dans le fichier qui a causé l'erreur, hérité depuis {{jsxref("Error")}}.</dd>
 <dt>{{jsxref("Error.prototype.columnNumber", "RangeError.prototype.columnNumber")}}</dt>
 <dd>La position du code (colonne) dans la ligne de code qui a causé l'erreur, héritée depuis {{jsxref("Error")}}.</dd>
 <dt>{{jsxref("Error.prototype.stack", "RangeError.prototype.stack")}}</dt>
 <dd>Pile d'appels, héritée depuis {{jsxref("Error")}}.</dd>
</dl>

<h2 id="Méthodes">Méthodes</h2>

<p>Bien que l'objet prototype {{jsxref("RangeError")}} ne possède pas de méthodes propres, les instances de <code>RangeError</code> hériteront de certaines méthodes via la chaîne de prototypes.</p>

<h2 id="Spécifications">Spécifications</h2>

<table class="standard-table">
 <tbody>
  <tr>
   <th scope="col">Spécification</th>
   <th scope="col">Statut</th>
   <th scope="col">Commentaires</th>
  </tr>
  <tr>
   <td>{{SpecName('ES3')}}</td>
   <td>{{Spec2('ES3')}}</td>
   <td>Définition initiale.</td>
  </tr>
  <tr>
   <td>{{SpecName('ES5.1', '#sec-15.11.7.6', 'NativeError.prototype')}}</td>
   <td>{{Spec2('ES5.1')}}</td>
   <td>Défini comme <code><em>NativeError</em>.prototype</code>.</td>
  </tr>
  <tr>
   <td>{{SpecName('ES6', '#sec-nativeerror.prototype', 'NativeError.prototype')}}</td>
   <td>{{Spec2('ES6')}}</td>
   <td>Défini comme <code><em>NativeError</em>.prototype</code>.</td>
  </tr>
  <tr>
   <td>{{SpecName('ESDraft', '#sec-nativeerror.prototype', 'NativeError.prototype')}}</td>
   <td>{{Spec2('ESDraft')}}</td>
   <td>Défini comme <code><em>NativeError</em>.prototype</code>.</td>
  </tr>
 </tbody>
</table>

<h2 id="Compatibilité_des_navigateurs">Compatibilité des navigateurs</h2>

<p>{{Compat("javascript.builtins.RangeError")}}</p>

<h2 id="Voir_aussi">Voir aussi</h2>

<ul>
 <li>{{jsxref("Error.prototype")}}</li>
 <li>{{jsxref("Function.prototype")}}</li>
</ul>
