---
title: TypeError
slug: Web/JavaScript/Reference/Global_Objects/TypeError
tags:
  - Error
  - JavaScript
  - Reference
  - TypeError
translation_of: Web/JavaScript/Reference/Global_Objects/TypeError
browser-compat: javascript.builtins.TypeError
---

<div>{{JSRef}}</div>

<p>
  <code><strong>TypeError</strong></code> 객체는 일반적으로 값이 기대하던 자료형이 아니라서 연산을 할 수 없을 때 발생하는 오류입니다.
</p>

<p>다음과 같은 경우 <code>TypeError</code>가 발생할 수 있습니다.</p>

<ul>
  <li>
    함수에 전달된 피연산자 또는 인수가 해당 연산자나 함수가 예상하는 타입과
    호환되지 않거나,
  </li>
  <li>변경할 수 없는 값을 수정하려고 하거나,</li>
  <li>부적절한 방법으로 값을 사용하려고 할 때.</li>
</ul>

<h2 id="Constructor">생성자</h2>

<dl>
  <dt>{{jsxref("Global_Objects/TypeError/TypeError", "TypeError()")}}</dt>
  <dd>새로운 <code>TypeError</code> 객체를 생성합니다.</dd>
</dl>

<h2 id="Instance_properties">인스턴스 속성</h2>

<dl>
  <dt>{{jsxref("Error.prototype.message", "TypeError.prototype.message")}}</dt>
  <dd>
    오류 메시지. 비록 ECMA-262에서 {{jsxref("TypeError")}}는 반드시 자체
    <code>message</code> 속성을 제공해야 한다고 명시했지만,
    <a href="/en-US/docs/Mozilla/Projects/SpiderMonkey">SpiderMonkey</a>는
    {{jsxref("Error.prototype.message")}}를 상속합니다.
  </dd>
  <dt>{{jsxref("Error.prototype.name", "TypeError.prototype.name")}}</dt>
  <dd>오류 이름. {{jsxref("Error")}}로부터 상속되었습니다.</dd>
  <dt>
    {{jsxref("Error.prototype.fileName", "TypeError.prototype.fileName")}}
  </dt>
  <dd>오류가 발생한 파일 경로. {{jsxref("Error")}}로부터 상속되었습니다.</dd>
  <dt>
    {{jsxref("Error.prototype.lineNumber", "TypeError.prototype.lineNumber")}}
  </dt>
  <dd>오류가 발생한 곳의 줄 위치. {{jsxref("Error")}}로부터 상속되었습니다.</dd>
  <dt>
    {{jsxref("Error.prototype.columnNumber", "TypeError.prototype.columnNumber")}}
  </dt>
  <dd>오류가 발생한 곳의 열 위치. {{jsxref("Error")}}로부터 상속되었습니다.</dd>
  <dt>{{jsxref("Error.prototype.stack", "TypeError.prototype.stack")}}</dt>
  <dd>스택 추적. {{jsxref("Error")}}로부터 상속되었습니다.</dd>
</dl>

<h2 id="Examples">예제</h2>

<h3 id="Catching_a_TypeError"><code>TypeError</code> 오류를 잡아내기</h3>

<pre class="brush: js">
try {
  null.f();
} catch (e) {
  console.log(e instanceof TypeError); // true
  console.log(e.message);              // "null has no properties"
  console.log(e.name);                 // "TypeError"
  console.log(e.fileName);             // "Scratchpad/1"
  console.log(e.lineNumber);           // 2
  console.log(e.columnNumber);         // 2
  console.log(e.stack);                // "@Scratchpad/2:2:3\n"
}
</pre>

<h3 id="Creating_a_TypeError"><code>TypeError</code> 오류를 생성하기</h3>

<pre class="brush: js">
try {
  throw new TypeError('Hello', "someFile.js", 10);
} catch (e) {
  console.log(e instanceof TypeError); // true
  console.log(e.message);              // "Hello"
  console.log(e.name);                 // "TypeError"
  console.log(e.fileName);             // "someFile.js"
  console.log(e.lineNumber);           // 10
  console.log(e.columnNumber);         // 0
  console.log(e.stack);                // "@Scratchpad/2:2:9\n"
}
</pre>

<h2 id="Specifications">명세</h2>

{{Specifications}}

<h2 id="Browser_compatibility">브라우저 호환성</h2>

<p>{{Compat}}</p>

<h2 id="See_also">같이 보기</h2>

<ul>
  <li>{{jsxref("Error")}}</li>
</ul>
